# Generated by Django 4.1.13 on 2024-07-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
