# Generated by Django 4.1.13 on 2024-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('inflation', models.FloatField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('literacy_rate', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('trade_balance', models.FloatField(blank=True, null=True)),
                ('foreign_direct_investment', models.FloatField(blank=True, null=True)),
                ('government_debt', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('literacy_rate', models.FloatField(blank=True, null=True)),
                ('school_enrollment_primary', models.FloatField(blank=True, null=True)),
                ('school_enrollment_secondary', models.FloatField(blank=True, null=True)),
                ('education_expenditure', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('labor_force_participation_rate', models.FloatField(blank=True, null=True)),
                ('employment_agriculture', models.FloatField(blank=True, null=True)),
                ('employment_industry', models.FloatField(blank=True, null=True)),
                ('employment_services', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('access_to_clean_water', models.FloatField(blank=True, null=True)),
                ('renewable_energy_consumption', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('life_expectancy', models.FloatField(blank=True, null=True)),
                ('mortality_rate_under_5', models.FloatField(blank=True, null=True)),
                ('health_expenditure', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='DDD', max_length=3)),
                ('poverty_headcount_ratio', models.FloatField(blank=True, null=True)),
                ('income_inequality_gini', models.FloatField(blank=True, null=True)),
                ('social_protection_coverage', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
