# Generated by Django 4.1.13 on 2024-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_currency_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('taker_side', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
