# Generated by Django 4.1.13 on 2024-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_location', models.CharField(max_length=255)),
                ('avg_stock_price_5yrs', models.FloatField()),
                ('avg_revenue_5yrs', models.FloatField()),
                ('percentage_change', models.FloatField()),
            ],
        ),
    ]
