# Generated by Django 4.1.13 on 2024-07-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='api_customuser',
        ),
    ]
